spring:
  kafka:
    producer:
      order:
        topic: tacocloud.orders.topic
        "[bootstrap.servers]": localhost:29888
        "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
        "[value.serializer]": sample.serializer.OrderSerializer
      taco:
        topic: tacocloud.tacos.topic
        "[bootstrap.servers]": localhost:29888
        "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
        "[value.serializer]": sample.serializer.TacoSerializer
    consumer:
      order:
        topic: tacocloud.orders.topic
        "[bootstrap.servers]": localhost:29888
        "[key.deserializer]": org.apache.kafka.common.serialization.StringDeserializer
        "[value.deserializer]": sample.serializer.OrderDeserializer
      taco:
        topic: tacocloud.tacos.topic
        "[bootstrap.servers]": localhost:29888
        "[key.deserializer]": org.apache.kafka.common.serialization.StringDeserializer
        "[value.deserializer]": sample.serializer.TacoDeserializer